



orgtypes = Organizationtype.create ([
                {name: 'Youth Forum'},
                {name: 'Womens Forum'},
                {name: 'Motorcyclists Forum'},
                {name: 'Traditional Council'},
                {name: 'Muslim Council'},
                {name: 'Christian Council'},
                {name: 'Government'},
                {name: 'USG'},
                {name: 'NGO'},
                {name: 'Disabled Community'},
                {name: 'Other'}
])



orgs = Organization.create ([
                {name: 'Judiciary', organizationtype_id: 7},
                {name: 'DEA', organizationtype_id: 7},
                {name: 'BIN', organizationtype_id: 0},
                {name: 'Superintendent', organizationtype_id: 7},
                {name: 'Land Commissioner', organizationtype_id: 7},
                {name: 'Ministry of Gender', organizationtype_id: 7},
                {name: 'LMA', organizationtype_id: 7},
                {name: 'Special Asst to Superintendent', organizationtype_id: 7}
])











peeps = Person.create([

{name_first: 'Sam N.', name_last: 'McGill',   gender: 1, structure_id: 2, community: 'Executive Drive, Gbarnga', agencyname: 'INCHR Monitor Supervisor'},
{name_first: 'Fasu V.', name_last: 'Sheriff ', salut: 'C/Supt. ',  gender: 1, structure_id: 27, community: 'New Zwedru', agencyname: 'LNP County lnp commander '},
{name_first: 'John D.', name_last: 'Walker',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'John F.', name_last: 'Deshield',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'John F.', name_last: 'Locukeh', salut: 'Ho.',  gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'John O.', name_last: 'Flomo',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'County Youth Coordinator'},
{name_first: 'Kolu V.', name_last: 'Jallah',   gender: 2, structure_id: 11, community: 'Vezala'},
{name_first: 'Kolu Y.', name_last: 'M. Beyan',   gender: 2, structure_id: 13, community: 'Fissebu'},
{name_first: 'Mark C.', name_last: 'Tarlue',   gender: 1, structure_id: 33, community: 'Ziah Town'},
{name_first: 'S. Zeor', name_last: 'Quaye',   gender: 2, structure_id: 33, community: 'Ziah Town'},
{name_first: 'Saah B.', name_last: 'Keylah', salut: 'Col',  gender: 1, structure_id: 7, community: 'Central Voinjama', agencyname: 'County BIN Commander'},
{name_first: 'Soko G.', name_last: 'Kamara',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Sumo F.', name_last: 'Koyia',   gender: 1, structure_id: 10, community: 'Vezala'},
{name_first: 'Wulu W.', name_last: 'Gaye',   gender: 1, structure_id: 33, community: 'Barwo'},
{name_first: 'Aaron S.', name_last: 'Kollie',   gender: 1, structure_id: 11, community: 'Massamai'},
{name_first: 'Annie S.', name_last: 'Dolokankan',   gender: 2, structure_id: 4, community: 'Kpaai Town'},
{name_first: 'David K.', name_last: 'Massah',   gender: 1, structure_id: 11, community: 'Molorvemai'},
{name_first: 'David K.', name_last: 'Subah ',   gender: 1, structure_id: 27, community: 'Kudah Byepass', agencyname: 'EPA County coordinator '},
{name_first: 'Edwin G.', name_last: 'Baysah',   gender: 1, structure_id: 11, community: 'Lawalazu'},
{name_first: 'Henry C.', name_last: 'Meiekamue',   gender: 1, structure_id: 5, community: 'Gbarnga'},
{name_first: 'Henry F.', name_last: 'Nyumah',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Allen D.', name_last: 'Tubah', salut: 'Hon.',  gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Peter L.', name_last: 'Solo', salut: 'Hon.',  gender: 1, structure_id: 27, community: 'New Zwedru', agencyname: 'County Superintendent'},
{name_first: 'Zubah K.', name_last: 'Johnson', salut: 'Hon.',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'J. Kowah', name_last: 'Farbalee',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Jacob B.', name_last: 'Duan',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'James B.', name_last: 'Flomo',   gender: 1, structure_id: 6, community: 'Raymondta'},
{name_first: 'James F.', name_last: 'Tellewoyan',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Acting Coordinator'},
{name_first: 'James Y.', name_last: 'Morlu',   gender: 1, structure_id: 7, community: 'Telbomai Quarter', agencyname: 'County MOYS Coordinator'},
{name_first: 'James Z.', name_last: 'Myers',   gender: 1, structure_id: 29, community: 'Nicko'},
{name_first: 'Korto K.', name_last: 'Mulbah',   gender: 2, structure_id: 13, community: 'Giziboigai'},
{name_first: 'James K.', name_last: 'Borbor', salut: 'Maj.',  gender: 1, structure_id: 5, community: 'Gbarnga'},
{name_first: 'Moses B.', name_last: 'Cheaawulu',   gender: 1, structure_id: 32, community: 'Boundary'},
{name_first: 'Moses S.', name_last: 'Kamara',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Moses W.', name_last: 'Gbayea',   gender: 1, structure_id: 31, community: 'Jarwodee'},
{name_first: 'Nancy K.', name_last: 'Nyain',   gender: 2, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Tamba D.', name_last: 'Flomo',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Albert T.', name_last: 'Siah',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Alfred N.', name_last: 'Dorbah',  suffix: 'Sr.', gender: 1, structure_id: 27, community: 'Kudah Byepass', agencyname: 'Land commissioner '},
{name_first: 'Arthur B.', name_last: 'Wennah',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Buston M.', name_last: 'Kolliegbo',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Daniel S.', name_last: 'Lebbie      ',   gender: 1, structure_id: 9, community: 'Nwor        '},
{name_first: 'Edward N.', name_last: 'Doe',   gender: 1, structure_id: 32, community: 'Barwo'},
{name_first: 'G. Mulbah', name_last: 'Zayzay',   gender: 1, structure_id: 11, community: 'Litisu'},
{name_first: 'George Q.', name_last: 'Daylue',   gender: 1, structure_id: 33, community: 'Glay Town'},
{name_first: 'Hannah G.', name_last: 'Paye',   gender: 2, structure_id: 4, community: 'Shilling Town'},
{name_first: 'Harris M.', name_last: 'Gaie',   gender: 1, structure_id: 6, community: 'Karyeata'},
{name_first: 'Harris Y.', name_last: 'Mulbah',   gender: 1, structure_id: 13, community: 'Wuomai'},
{name_first: 'Edward T.', name_last: 'Yarkpawolo', salut: 'Hon.',  gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Commissioner Council Representative'},
{name_first: 'George S.', name_last: 'Dunor', salut: 'Hon.',  gender: 1, structure_id: 7, community: 'Doe Hill', agencyname: 'County Superintendent'},
{name_first: 'Joseph T.', name_last: 'Gbollie', salut: 'Hon.',  gender: 1, structure_id: 7, community: 'Foya (outside)', agencyname: 'Commissioners Council Chair'},
{name_first: 'Joseph T.', name_last: 'Gbollie', salut: 'Hon.',  gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'J. Dorbor', name_last: 'Flomo',   gender: 1, structure_id: 13, community: 'Barziwein'},
{name_first: 'J. Melvin', name_last: 'Tokpah',   gender: 1, structure_id: 6, community: 'Balama'},
{name_first: 'J. Milton', name_last: 'Dormue',   gender: 1, structure_id: 4, community: 'Tarsah'},
{name_first: 'J. Mulbah', name_last: 'Koiyan',   gender: 1, structure_id: 11, community: 'Vonema'},
{name_first: 'J. Tarnue', name_last: 'Sumo',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Joseph B.', name_last: 'Flomo',   gender: 1, structure_id: 13, community: 'Zolowo'},
{name_first: 'Joseph F.', name_last: 'Jallah',   gender: 1, structure_id: 11, community: 'Vezala'},
{name_first: 'Joseph M.', name_last: 'Urey',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Administrative Assistant'},
{name_first: 'Joseph W.', name_last: 'Sumo ',   gender: 1, structure_id: 27, community: 'National Palace of Corrections', agencyname: 'Director. Palace of corrections '},
{name_first: 'Joseph W.', name_last: 'Tarlue',   gender: 1, structure_id: 32, community: 'Wulu'},
{name_first: 'Joseph W.', name_last: 'Tarlue ', salut: 'Pc.',  gender: 1, structure_id: 27, community: 'Boundary Town, Konobo District', agencyname: 'Paramount chief council '},
{name_first: 'Joseph W.', name_last: 'Zelee',   gender: 1, structure_id: 32, community: 'Peah'},
{name_first: 'K. Nelson', name_last: 'Saydee',   gender: 1, structure_id: 29, community: 'Blown Town'},
{name_first: 'Mulbah G.', name_last: 'Agbawoi',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Olaska W.', name_last: 'Barh ',   gender: 1, structure_id: 27, community: 'Sinoe Road', agencyname: 'Administrative Assistant '},
{name_first: 'Oliver D.', name_last: 'Weagba',   gender: 1, structure_id: 29, community: 'BHai Tarway'},
{name_first: 'Edward Q.', name_last: 'Delayee', salut: 'Pst.',  gender: 1, structure_id: 33, community: 'Boundary'},
{name_first: 'T. Karsor', name_last: 'Jarboi',   gender: 1, structure_id: 11, community: 'Balakpalasu'},
{name_first: 'Woizoa G.', name_last: 'Kollie',   gender: 1, structure_id: 11, community: 'Dougomai'},
{name_first: 'Zorgbo W.', name_last: 'Zaza',   gender: 2, structure_id: 13, community: 'Konia'},
{name_first: 'Agathan S.', name_last: 'Fayombo  ',   gender: 2, structure_id: 9, community: 'Kpandu    '},
{name_first: 'Alfried L.', name_last: 'Koikoi',   gender: 1, structure_id: 11, community: 'Bawomai'},
{name_first: 'Anthony G.', name_last: 'Toe Jr. ',  suffix: 'Jr.', gender: 1, structure_id: 33, community: 'Peah'},
{name_first: 'Anthony G.', name_last: 'Toe Sr. ',  suffix: 'Sr.', gender: 1, structure_id: 32, community: 'Peah'},
{name_first: 'Charles F.', name_last: 'King',  suffix: 'Sr.', gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Land Commissioner'},
{name_first: 'Romeo', name_last: 'Wolo', salut: 'Col. ',  gender: 1, structure_id: 27, community: 'City hall community', agencyname: 'DEA/ county commander '},
{name_first: 'William A.', name_last: 'Koteah', salut: 'Col. ', suffix: 'Sr.', gender: 1, structure_id: 27, community: 'Sinoe Road', agencyname: 'Bin commander '},
{name_first: 'E. Wilbert', name_last: 'Gee',   gender: 1, structure_id: 31, community: 'Jarwodee'},
{name_first: 'E. Wilkins', name_last: 'Nah',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'County Attorney'},
{name_first: 'Emmette W.', name_last: 'Waylee',   gender: 1, structure_id: 33, community: 'Wulu'},
{name_first: 'Francis M.', name_last: 'Dunor',   gender: 1, structure_id: 7, community: 'Doe Hill', agencyname: 'Supt  Admin. Assistant'},
{name_first: 'G. Wilkins', name_last: 'Gaou ',   gender: 1, structure_id: 27, community: 'Towah Street', agencyname: 'County protocol officer '},
{name_first: 'G. Wolobah', name_last: 'Dorbor',   gender: 1, structure_id: 10, community: 'Lawalazu'},
{name_first: 'J. Madason', name_last: 'Tarplain',   gender: 1, structure_id: 3, community: 'Zoweinta'},
{name_first: 'Jackson B.', name_last: 'Quinwon',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Moses', name_last: 'Neah',   gender: 1, structure_id: 27, community: 'Pennue Community', agencyname: 'MOGSP County coordinator '},
{name_first: 'Patrick M.', name_last: 'Kollie', salut: 'Sr. ',  gender: 1, structure_id: 11, community: 'Kpangbalamai'},
{name_first: 'S. Karkuan', name_last: 'Ziamo',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Sampson C.', name_last: 'Dulue',   gender: 1, structure_id: 32, community: 'Glay Town'},
{name_first: 'Solomon B.', name_last: 'Moore',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Solomon S.', name_last: 'Pajibo',   gender: 1, structure_id: 29, community: 'Toe Town'},
{name_first: 'Steohen D.', name_last: 'Kollie',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'William B.', name_last: 'S Kollie',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'County Inspector'},
{name_first: 'William G.', name_last: 'Tarpeh',   gender: 1, structure_id: 32, community: 'Barwo'},
{name_first: 'William N.', name_last: 'Kollie',   gender: 1, structure_id: 4, community: 'Shilling Town'},
{name_first: 'Adolphus S.', name_last: 'Zloryoou',   gender: 1, structure_id: 29, community: 'Tian Town'},
{name_first: 'Arthur T.Y.', name_last: 'Kanswe',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Arthur T.Y.', name_last: 'Kanswe ',   gender: 1, structure_id: 27, community: 'Zleh Town, Gbao District', agencyname: 'Chair/commisioner council '},
{name_first: 'Elder David', name_last: 'Nebo ',   gender: 1, structure_id: 27, community: 'Admin. Building', agencyname: 'National Traditional Council Chair'},
{name_first: 'Emmanuel S.', name_last: 'Soe',   gender: 1, structure_id: 29, community: 'BHai Jorzon'},
{name_first: 'G. Emmanuel D.', name_last: 'Kollie', salut: 'G.',  gender: 1, structure_id: 11, community: 'Dayzabah'},
{name_first: 'J. Josephus', name_last: 'Morris',   gender: 1, structure_id: 31, community: 'Teladee'},
{name_first: 'Jeremiah J.', name_last: 'Kyne',   gender: 1, structure_id: 28, community: 'Sennehwen'},
{name_first: 'Josephus K.', name_last: 'Garley ',   gender: 1, structure_id: 27, community: 'Gboleken Town', agencyname: 'County inspector '},
{name_first: 'Justonue D.', name_last: 'Mulbah',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Lt Toogbabu', name_last: 'Toogbabu ', salut: 'Lt.',  gender: 1, structure_id: 27, community: 'Camp. Wisner', agencyname: 'AFL County commander '},
{name_first: 'Ruth Milton', name_last: 'Milton ', salut: 'Madam',  gender: 2, structure_id: 27, community: 'Sinoe Road', agencyname: 'BOVA County coordinator '},
{name_first: 'Anthony Wulu', name_last: 'Wulu ',   gender: 1, structure_id: 27, community: 'Kudah Byepass', agencyname: 'MOYS County coordinator '},
{name_first: 'Dixon Robert', name_last: 'Robert ',   gender: 1, structure_id: 31, community: 'Tojalah Town'},
{name_first: 'Evelyn Weyea', name_last: 'Weyea ',   gender: 2, structure_id: 31, community: 'Pouh'},
{name_first: 'Frederick D.', name_last: 'Neppy',   gender: 1, structure_id: 2, community: 'Rubber Factory, Gbarnga', agencyname: 'LNP Commander'},
{name_first: 'Mariah Youlo', name_last: 'Youlo ',   gender: 2, structure_id: 33, community: 'Dejalah'},
{name_first: 'Harris Puiyoe', name_last: 'Puiyoe        ',   gender: 1, structure_id: 9, community: 'Tormadu   '},
{name_first: 'Serena Polson', name_last: 'Mappy', salut: 'Hon.',  gender: 2, structure_id: 2, community: 'Civil Compound, Gbarnga', agencyname: 'County Superintendent'},
{name_first: 'Jolly Neewray', name_last: 'Neewray ',   gender: 2, structure_id: 29, community: 'Sennehwen'},
{name_first: 'Marthaline K.', name_last: 'Kollie',   gender: 2, structure_id: 3, community: 'Palala'},
{name_first: 'Tarnue Jallah', name_last: 'Jallah ',   gender: 1, structure_id: 11, community: 'Bakuma'},
{name_first: 'Augustine A.K.', name_last: 'Momoh',   gender: 1, structure_id: 7, community: 'Hospital Community', agencyname: 'County Land Commissioner'},
{name_first: 'Jefferson Tweh', name_last: 'Tweh ', salut: 'Col. ',  gender: 1, structure_id: 27, community: 'City hall community', agencyname: 'Lib. National Fire Service/ commander '},
{name_first: 'Sampson Pennue', name_last: 'Pennue ', salut: 'Col. ',  gender: 1, structure_id: 27, community: 'Towah Street', agencyname: 'NSA County commander '},
{name_first: 'Emmanuel Smith', name_last: 'Smith ',   gender: 1, structure_id: 31, community: 'Kweoh'},
{name_first: 'Fayiah Nyorkor', name_last: 'Nyorkor      ',   gender: 1, structure_id: 9, community: 'Sadu Passia'},
{name_first: 'Felicia Duncan', name_last: 'Duncan ', salut: 'Madam',  gender: 2, structure_id: 27, community: 'Sinoe Road', agencyname: 'CSO/ coordinator '},
{name_first: 'Patrick Manjoe', name_last: 'Manjoe ',   gender: 1, structure_id: 7, community: 'Administrative Cpd.', agencyname: 'Protocol Officer'},
{name_first: 'Emmanuel Sackor', name_last: 'Sackor ',   gender: 1, structure_id: 31, community: 'Juluzon'},
{name_first: 'Jessedeh Barzon', name_last: 'Barzon ', salut: 'Madam',  gender: 2, structure_id: 27, community: 'Naio Community', agencyname: 'Rural Women President '},
{name_first: 'Quoiquoi Miller', name_last: 'Miller ',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Soefieh Russell', name_last: 'Russell ',   gender: 1, structure_id: 31, community: 'Deblay'},
{name_first: 'Hezekiah Berlarh', name_last: 'Berlarh ',   gender: 1, structure_id: 33, community: 'Druwar'},
{name_first: 'Patience Jonhnny', name_last: 'Jonhnny ',   gender: 2, structure_id: 31, community: 'Jarwodee'},
{name_first: 'Sylvester', name_last: 'Amankwah ',   gender: 1, structure_id: 31, community: 'Barker Town'},
{name_first: 'Abdul', name_last: 'Jallahquoi',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Abel', name_last: 'Kartoe',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Agartha', name_last: 'Zarway',   gender: 2, structure_id: 31, community: 'Gaye Town'},
{name_first: 'Alexander', name_last: 'Quenneh',   gender: 1, structure_id: 4, community: 'Duta'},
{name_first: 'Alexander', name_last: 'Wolobah',   gender: 1, structure_id: 10, community: 'Vezala'},
{name_first: 'Alfred', name_last: 'Chayee',   gender: 1, structure_id: 31, community: 'Zuajah'},
{name_first: 'Alice', name_last: 'Queweay',   gender: 2, structure_id: 31, community: 'Polar '},
{name_first: 'Alice', name_last: 'Yuwar',   gender: 2, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Alvin', name_last: 'Jearue',   gender: 1, structure_id: 29, community: 'Dougee'},
{name_first: 'Andrew', name_last: 'Akoi',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Andrew', name_last: 'Tamba',   gender: 1, structure_id: 9, community: 'Worsonga'},
{name_first: 'Annie', name_last: 'Belekollie',   gender: 2, structure_id: 4, community: 'Duta'},
{name_first: 'Annie', name_last: 'Lakpasiyou',   gender: 2, structure_id: 9, community: 'Lengbamba'},
{name_first: 'Anthony', name_last: 'Beyon',   gender: 1, structure_id: 11, community: 'Konadu'},
{name_first: 'Anthony', name_last: 'Dorbor',   gender: 1, structure_id: 11, community: 'Kugbemai'},
{name_first: 'Anthony', name_last: 'Kormah',   gender: 1, structure_id: 11, community: 'Kaligizia'},
{name_first: 'Anthony', name_last: 'Tolbert',   gender: 1, structure_id: 2, community: 'Bassa Community, Gbarnga', agencyname: 'Deputy NSA County Commander'},
{name_first: 'Ateo', name_last: 'Gaylah',   gender: 1, structure_id: 31, community: 'Zaliken'},
{name_first: 'Augustine', name_last: 'Kpellewo',   gender: 1, structure_id: 9, community: 'Korndobengu'},
{name_first: 'Augustine', name_last: 'Nyumah',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Augustine', name_last: 'Sackie',   gender: 1, structure_id: 6, community: 'Gbarngai'},
{name_first: 'Austin', name_last: 'Decee',   gender: 1, structure_id: 29, community: 'Sennehwen'},
{name_first: 'Austin', name_last: 'Wamah',   gender: 1, structure_id: 29, community: 'Kpelleh Village'},
{name_first: 'Awee', name_last: 'Williewu',   gender: 1, structure_id: 6, community: 'Phebe'},
{name_first: 'Baindu', name_last: 'Boakai',   gender: 2, structure_id: 9, community: 'Paywahun'},
{name_first: 'Barlee', name_last: 'Torh',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Bassah', name_last: 'Tellewoyan',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Belleh', name_last: 'Krayou',   gender: 1, structure_id: 33, community: 'Ziah Town'},
{name_first: 'Belleh', name_last: 'Quaye',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Betty', name_last: 'Peal',   gender: 2, structure_id: 29, community: 'BHai Jorzon'},
{name_first: 'Bigboy', name_last: 'Kokulo',   gender: 1, structure_id: 13, community: 'Woizie'},
{name_first: 'Bigman', name_last: 'Harris',   gender: 1, structure_id: 13, community: 'Kpassagizia'},
{name_first: 'Williams', name_last: 'Tarty', salut: 'Bishop',  gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Boima', name_last: 'Powoe',   gender: 1, structure_id: 9, community: 'Kongbama'},
{name_first: 'Borbor', name_last: 'Gissi',   gender: 1, structure_id: 4, community: 'David Town'},
{name_first: 'Calor', name_last: 'Beh',   gender: 2, structure_id: 31, community: 'Gbeayea'},
{name_first: 'Calvin', name_last: 'Brown',   gender: 1, structure_id: 28, community: 'BHai Jorzon'},
{name_first: 'Otis', name_last: 'Gesee', salut: 'Capt. ',  gender: 1, structure_id: 3, community: 'Gbarnga'},
{name_first: 'Cecelia', name_last: 'Gboloe',   gender: 2, structure_id: 31, community: 'Cheansla'},
{name_first: 'Cecelia', name_last: 'Hallie',   gender: 2, structure_id: 8, community: 'Foya City'},
{name_first: 'Chea', name_last: 'Quaye',   gender: 1, structure_id: 33, community: 'Glay Town'},
{name_first: 'Cheatyson', name_last: 'Tarty',   gender: 1, structure_id: 31, community: 'Zleh Town'},
{name_first: 'Christian', name_last: 'Bannah',   gender: 1, structure_id: 12, community: 'Wuomai'},
{name_first: 'Christiana', name_last: 'Bassah',   gender: 2, structure_id: 31, community: 'Gbakeh'},
{name_first: 'Christiana', name_last: 'Gowen',   gender: 2, structure_id: 29, community: 'Bah Town'},
{name_first: 'Christiana', name_last: 'Tarpeh',   gender: 2, structure_id: 29, community: 'Giah'},
{name_first: 'Christopher', name_last: 'Kollie',   gender: 1, structure_id: 6, community: 'Sinyea'},
{name_first: 'Ciah', name_last: 'Tarley',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Clinton', name_last: 'Tope',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Luther', name_last: 'Sumo', salut: 'Cllr.',  gender: 1, structure_id: 7, community: 'Army Barrack', agencyname: 'County Attorney'},
{name_first: 'George', name_last: 'Poney', salut: 'Col. ',  gender: 1, structure_id: 7, community: 'Kolahun Parking', agencyname: 'County DEA Commander'},
{name_first: 'James', name_last: 'Sieh', salut: 'Col. ',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Richard', name_last: 'Steward', salut: 'Col. ',  gender: 1, structure_id: 7, community: 'Kissi Quarter', agencyname: 'County NSA Commander'},
{name_first: 'Confort', name_last: 'Gbaryou',   gender: 2, structure_id: 33, community: 'Sentrudru'},
{name_first: 'Cynthia', name_last: 'Tarley',   gender: 2, structure_id: 33, community: 'Deleayee'},
{name_first: 'Daniel', name_last: 'Dukai',   gender: 1, structure_id: 6, community: 'Gokai'},
{name_first: 'Daniel', name_last: 'Neewray',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Daniel', name_last: 'Sumo',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Daniel', name_last: 'Wondee',   gender: 1, structure_id: 30, community: 'Pouh'},
{name_first: 'Darius', name_last: 'Paye',   gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'DEA Commander'},
{name_first: 'David', name_last: 'Kollie',   gender: 1, structure_id: 4, community: 'Melenta'},
{name_first: 'David', name_last: 'Kordor',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'David', name_last: 'Kpannah',   gender: 1, structure_id: 4, community: 'Baila'},
{name_first: 'David', name_last: 'Mawolo',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Dedeh', name_last: 'Smith',   gender: 2, structure_id: 11, community: 'Larborlorzu Town'},
{name_first: 'Dehora', name_last: 'Sandy',   gender: 1, structure_id: 29, community: 'Giah'},
{name_first: 'Dehwye', name_last: 'Dorbor',   gender: 2, structure_id: 33, community: 'Sayuo Town'},
{name_first: 'Doris', name_last: 'Juan',   gender: 2, structure_id: 28, community: 'Toe Town'},
{name_first: 'Edna', name_last: 'Duo',   gender: 2, structure_id: 28, community: 'Toe Town'},
{name_first: 'Elijah', name_last: 'Gaye',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Elizer', name_last: 'Gee',   gender: 2, structure_id: 33, community: 'Boundary'},
{name_first: 'Emmanuel', name_last: 'Dorber',   gender: 1, structure_id: 33, community: 'Juwar'},
{name_first: 'Emmanuel', name_last: 'Kalkpo',   gender: 1, structure_id: 6, community: 'SKT'},
{name_first: 'Emmanuel', name_last: 'Krayee',   gender: 1, structure_id: 28, community: 'Dougee'},
{name_first: 'Emmanuel', name_last: 'Weah',   gender: 1, structure_id: 28, community: 'BHai Jorzon'},
{name_first: 'Esther', name_last: 'Gbarjah',   gender: 2, structure_id: 4, community: 'David Town'},
{name_first: 'Esther', name_last: 'Sandy',   gender: 2, structure_id: 29, community: 'Blown Town'},
{name_first: 'Esther', name_last: 'Waylee',   gender: 2, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Esther', name_last: 'Weefah',   gender: 2, structure_id: 8, community: 'Foya City'},
{name_first: 'Etta', name_last: 'Duolo',   gender: 2, structure_id: 33, community: 'Tuglor'},
{name_first: 'Evelyn', name_last: 'Karyee',   gender: 2, structure_id: 29, community: 'Nicko'},
{name_first: 'Evelyn', name_last: 'Pour',   gender: 2, structure_id: 29, community: 'BHai Tarway'},
{name_first: 'Ezekiel', name_last: 'Bayloe',   gender: 1, structure_id: 9, community: 'Chargboma'},
{name_first: 'Farsama', name_last: 'Dorbor',   gender: 1, structure_id: 11, community: 'Zawordamai'},
{name_first: 'Fatu', name_last: 'Jayah',   gender: 2, structure_id: 8, community: 'Foya City'},
{name_first: 'Fatu', name_last: 'Kamara',   gender: 2, structure_id: 13, community: 'Ziggida'},
{name_first: 'Fayia', name_last: 'Kulloe',   gender: 1, structure_id: 9, community: 'Yengbemai'},
{name_first: 'Felicia', name_last: 'Tarpeh',   gender: 2, structure_id: 33, community: 'Wrabo'},
{name_first: 'Flomo', name_last: 'Johnson',   gender: 1, structure_id: 7, community: 'Market Community', agencyname: 'Correction Superintendent'},
{name_first: 'Foday', name_last: 'Konneh',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Forkpa', name_last: 'Willison',   gender: 1, structure_id: 13, community: 'Vitesu'},
{name_first: 'Francis', name_last: 'Gbelawoe',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Francise', name_last: 'Barkayee',   gender: 2, structure_id: 31, community: 'Zaliken'},
{name_first: 'Gaimah', name_last: 'Gbelawoe',   gender: 2, structure_id: 5, community: 'Suakoko '},
{name_first: 'Garmai', name_last: 'Wolobah',   gender: 2, structure_id: 13, community: 'Wuomai'},
{name_first: 'Gbarko', name_last: 'Mulbah',   gender: 1, structure_id: 6, community: 'Nai'},
{name_first: 'Abraham', name_last: 'Borlor', salut: 'Gen.',  gender: 1, structure_id: 7, community: 'Administrative Cpd.', agencyname: 'Aide - de - Camp '},
{name_first: 'George', name_last: 'A.Teway',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'George', name_last: 'Davis',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'George', name_last: 'Flomo',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'George', name_last: 'Gbarwea',   gender: 1, structure_id: 28, community: 'BHai Tarway'},
{name_first: 'George', name_last: 'Kamara',   gender: 1, structure_id: 6, community: 'Phebe'},
{name_first: 'George', name_last: 'Krajayee',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Glayee', name_last: 'Karr',   gender: 1, structure_id: 30, community: 'Pouh'},
{name_first: 'Gormah', name_last: 'Deikelen',   gender: 2, structure_id: 4, community: 'Gatayea'},
{name_first: 'Gormah', name_last: 'Kokoyah',   gender: 2, structure_id: 6, community: 'Gallah'},
{name_first: 'Gormah', name_last: 'Vartekeh',   gender: 2, structure_id: 4, community: 'Baila'},
{name_first: 'Guwor', name_last: 'Kollie', salut: 'Cpt.',  gender: 1, structure_id: 7, community: 'Karza Quarter', agencyname: 'County LNFS Commander'},
{name_first: 'Habakkuk', name_last: 'Kollie',   gender: 1, structure_id: 4, community: 'Zebay'},
{name_first: 'Harris', name_last: 'Chayee',   gender: 1, structure_id: 30, community: 'Gaye Town'},
{name_first: 'Harris', name_last: 'Domah',   gender: 1, structure_id: 9, community: 'Sorlumba'},
{name_first: 'Harry', name_last: 'Garnyean',   gender: 1, structure_id: 3, community: 'Zebay'},
{name_first: 'Henry', name_last: 'Zazaboi',   gender: 1, structure_id: 13, community: 'Luyeama'},
{name_first: 'Abraham', name_last: 'Kantee', salut: 'Hon.',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Clydius', name_last: 'Saul', salut: 'Hon.',  gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Henry', name_last: 'Mbetor', salut: 'Hon.',  gender: 1, structure_id: 3, community: 'Gatayea'},
{name_first: 'Henry', name_last: 'Wolubah', salut: 'Hon.',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Henry', name_last: 'Zayzay', salut: 'Hon.',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Momoh', name_last: 'Taylor', salut: 'Hon.',  gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Moses', name_last: 'Suakollie', salut: 'Hon.',  gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Traditional Council'},
{name_first: 'Musa', name_last: 'Kamara', salut: 'Hon.',  gender: 1, structure_id: 7, community: 'Barkedou (outside)', agencyname: 'Paramount Chiefs Council Chairperson'},
{name_first: 'Tennyson', name_last: 'Fakonia', salut: 'Hon.',  gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Togar', name_last: 'Glegbo', salut: 'Hon.',  gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Paramount Chief'},
{name_first: 'Kullie', name_last: 'M.Barzie', salut: 'Hon.',  gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'I.Youboty', name_last: 'Garley',   gender: 1, structure_id: 32, community: 'Wulu'},
{name_first: 'Isaac', name_last: 'Cooper',   gender: 1, structure_id: 29, community: 'Bah Town'},
{name_first: 'Isaac', name_last: 'Yarlue',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Ishmael', name_last: 'Kamara',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Jackson', name_last: 'Sohn',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Jallah', name_last: 'Yenneh',   gender: 1, structure_id: 11, community: 'Lawalazu'},
{name_first: 'James', name_last: 'Korboi',   gender: 1, structure_id: 7, community: 'Free Pentecostal Cpd.', agencyname: 'Representative of CSOs'},
{name_first: 'James', name_last: 'Kpoquoi',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'James', name_last: 'Quewea',   gender: 1, structure_id: 30, community: 'Juluzon '},
{name_first: 'James', name_last: 'Tamba',   gender: 1, structure_id: 9, community: 'Kelemabendu'},
{name_first: 'James', name_last: 'Yarkpawolo',   gender: 1, structure_id: 6, community: 'Raymondta'},
{name_first: 'Jerry', name_last: 'Flomo',   gender: 1, structure_id: 6, community: 'SKT'},
{name_first: 'Jerry', name_last: 'Gbozee',   gender: 1, structure_id: 13, community: 'Zelemai'},
{name_first: 'Jimel', name_last: 'Kamara',   gender: 1, structure_id: 7, community: 'New Voinjama', agencyname: 'County Inspector'},
{name_first: 'Joanna', name_last: 'Tye',   gender: 2, structure_id: 29, community: 'Dougee'},
{name_first: 'John', name_last: 'Kaih',   gender: 1, structure_id: 28, community: 'Nicko'},
{name_first: 'John', name_last: 'Kokulo', salut: 'Capt.',  gender: 1, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'AFL - Gbarnga'},
{name_first: 'John', name_last: 'Kollie',   gender: 1, structure_id: 6, community: 'Gallah'},
{name_first: 'John', name_last: 'Kolliemene',   gender: 1, structure_id: 2, community: 'Bassa Community, Gbarnga', agencyname: 'Executive Protective Service'},
{name_first: 'John', name_last: 'Luckie',   gender: 1, structure_id: 2, community: 'Lofa Community, Gbarnga', agencyname: 'Regional Hub Representative'},
{name_first: 'John', name_last: 'Mahn',   gender: 1, structure_id: 3, community: 'Zoweinta'},
{name_first: 'Johnson', name_last: 'Dargbay',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Jonah', name_last: 'Blama',   gender: 1, structure_id: 29, community: 'Dougee'},
{name_first: 'Joseph', name_last: 'Bulleh',   gender: 1, structure_id: 33, community: 'Sentrudru'},
{name_first: 'Joseph', name_last: 'Kpantee',   gender: 1, structure_id: 2, community: 'Brooklyn Community, Gbarnga', agencyname: 'Acting EPA County Coordinator'},
{name_first: 'Joseph', name_last: 'Kyne',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Joseph', name_last: 'Momo',   gender: 1, structure_id: 11, community: 'Wotola'},
{name_first: 'Joseph', name_last: 'Seazia',   gender: 1, structure_id: 11, community: 'Alijazu'},
{name_first: 'Joseph', name_last: 'Togbah',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Josephus', name_last: 'Gbarnjah',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Joshua', name_last: 'Samuel',   gender: 1, structure_id: 33, community: 'Tuglor'},
{name_first: 'Junior', name_last: 'Chayee',   gender: 1, structure_id: 29, community: 'Goyezon'},
{name_first: 'Justina', name_last: 'Pah',   gender: 2, structure_id: 29, community: 'Goyezon'},
{name_first: 'Juwoe', name_last: 'Endee',   gender: 1, structure_id: 6, community: 'Yarwalee'},
{name_first: 'Kagnah', name_last: 'Mulbah',   gender: 2, structure_id: 6, community: 'Gwenimah'},
{name_first: 'Kennedy', name_last: 'Willie',   gender: 1, structure_id: 6, community: 'Karyeata'},
{name_first: 'Kerbeh', name_last: 'Bendu',   gender: 2, structure_id: 13, community: 'Zealakpaila'},
{name_first: 'Kezelee-Ballah', name_last: 'Zaza',   gender: 1, structure_id: 13, community: 'Ziggida'},
{name_first: 'Kollie', name_last: 'Sermah',   gender: 1, structure_id: 11, community: 'David Selmai Town'},
{name_first: 'Komassa', name_last: 'Jallah',   gender: 2, structure_id: 10, community: 'Voinjama'},
{name_first: 'Korpo', name_last: 'Zoboi',   gender: 2, structure_id: 10, community: 'Voinjama'},
{name_first: 'Korquelleh', name_last: 'Yarkpawolo',   gender: 1, structure_id: 6, community: 'Gbarngai'},
{name_first: 'Kpana', name_last: 'Leopord',   gender: 2, structure_id: 9, community: 'Porluma '},
{name_first: 'Kpoto', name_last: 'Jimmy',   gender: 1, structure_id: 9, community: 'Jomata'},
{name_first: 'Krubo', name_last: 'Deddeh',   gender: 2, structure_id: 13, community: 'Malawu'},
{name_first: 'Krubo', name_last: 'Gbaway',   gender: 2, structure_id: 13, community: 'Zulor'},
{name_first: 'Krubo', name_last: 'Mulbah',   gender: 2, structure_id: 13, community: 'Kpassagizia'},
{name_first: 'Krubo', name_last: 'Yaya',   gender: 2, structure_id: 13, community: 'Borkeza'},
{name_first: 'Kullie', name_last: 'Paywala',   gender: 1, structure_id: 11, community: 'Zenalormai'},
{name_first: 'Laiyee', name_last: 'Konnah',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Larwuo', name_last: 'Wonnie',   gender: 2, structure_id: 13, community: 'Yeala'},
{name_first: 'Lasana', name_last: 'Fofana',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Lasana', name_last: 'Kamarah',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Lewis', name_last: 'Garsayale',   gender: 2, structure_id: 4, community: 'Zebay'},
{name_first: 'Lincoln', name_last: 'Yanrue',  suffix: 'Sr.', gender: 1, structure_id: 31, community: 'Pouh'},
{name_first: 'Lorpu', name_last: 'Flomo',   gender: 2, structure_id: 12, community: 'Zorzor'},
{name_first: 'Lovely', name_last: 'Nyain',   gender: 2, structure_id: 31, community: 'Zleh Town'},
{name_first: 'D', name_last: 'Nuah', salut: 'Ltd.',  gender: 1, structure_id: 28, community: 'BHai Jorzon'},
{name_first: 'Beward', name_last: 'Korta', salut: 'Ma ',  gender: 2, structure_id: 13, community: 'Kailemai'},
{name_first: 'Kurbo', name_last: 'Zaza', salut: 'Ma ',  gender: 2, structure_id: 13, community: 'Kelewu'},
{name_first: 'Mabel', name_last: 'Gaye',   gender: 2, structure_id: 31, community: 'Tojalah Town'},
{name_first: 'Mabentu', name_last: 'Dukulay',   gender: 2, structure_id: 13, community: 'Zorzor'},
{name_first: 'Anita', name_last: 'Rennie', salut: 'Madam',  gender: 2, structure_id: 2, community: 'Lelehkpayea Community, Gbarnga', agencyname: 'Gender Coordinator'},
{name_first: 'Eugene', name_last: 'Quiah', salut: 'Maj.',  gender: 1, structure_id: 3, community: 'Gbarnga'},
{name_first: 'Othello', name_last: 'Kolliegbo', salut: 'Maj.',  gender: 1, structure_id: 5, community: 'Gbarnga'},
{name_first: 'Mama', name_last: 'Gayah',   gender: 2, structure_id: 12, community: 'Zorzor'},
{name_first: 'Mama', name_last: 'Tarnue',   gender: 2, structure_id: 13, community: 'Konia'},
{name_first: 'Mamadee', name_last: 'Kamara',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Mamie', name_last: 'Gbayo',   gender: 2, structure_id: 29, community: 'Toe Town'},
{name_first: 'Mananey', name_last: 'Tamba',   gender: 1, structure_id: 9, community: 'Mendikorma'},
{name_first: 'Marhta', name_last: 'Cole',   gender: 2, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Mark', name_last: 'Barjibo',   gender: 1, structure_id: 29, community: 'Tian Town'},
{name_first: 'Mark', name_last: 'Fallah',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Mark', name_last: 'Fayiah',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Mark', name_last: 'Koryeyan',   gender: 1, structure_id: 33, community: 'Boundary'},
{name_first: 'Martha', name_last: 'Ricks',   gender: 2, structure_id: 6, community: 'Sinyea'},
{name_first: 'Mary', name_last: 'Yeyea',   gender: 2, structure_id: 9, community: 'Borliloe'},
{name_first: 'Massayan', name_last: 'Didi',   gender: 1, structure_id: 11, community: 'Johnny Town'},
{name_first: 'Massayan', name_last: 'Saizia',   gender: 1, structure_id: 11, community: 'Betijama'},
{name_first: 'Matthew', name_last: 'Kerkulah',   gender: 1, structure_id: 6, community: 'Raymondta'},
{name_first: 'Mawolo', name_last: 'Kollie',   gender: 1, structure_id: 11, community: 'Kpakuta'},
{name_first: 'Mekay', name_last: 'Brown',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Melvina', name_last: 'Sandy',   gender: 2, structure_id: 29, community: 'Tian Town'},
{name_first: 'Michael', name_last: 'Ballah',   gender: 1, structure_id: 10, community: 'Vezala'},
{name_first: 'Milton', name_last: 'Gee',   gender: 1, structure_id: 33, community: 'Dweh Town'},
{name_first: 'Mohafee', name_last: 'Jabateh',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Mohammed', name_last: 'Keita',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Moifee', name_last: 'Tulay',   gender: 1, structure_id: 9, community: 'Foya Tengia'},
{name_first: 'Morris', name_last: 'Dulleh',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Moses', name_last: 'Daingbowah',   gender: 1, structure_id: 6, community: 'Gwenimah'},
{name_first: 'Moses', name_last: 'Daniyelleh',   gender: 1, structure_id: 4, community: 'Gatayea'},
{name_first: 'Moses', name_last: 'Gbayan',   gender: 1, structure_id: 4, community: 'Zebay'},
{name_first: 'Moses', name_last: 'Kullie',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Moses', name_last: 'Meiporkoyah',   gender: 1, structure_id: 4, community: 'Saworlor'},
{name_first: 'Moses', name_last: 'Nimely',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Moses', name_last: 's.Wologbo',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Moses', name_last: 'Tatoe',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Moses', name_last: 'Yowoe',   gender: 1, structure_id: 9, community: 'Sodu'},
{name_first: 'Forkpah', name_last: 'Boakai', salut: 'Mr.',  gender: 1, structure_id: 7, community: 'Telbomai Quarter', agencyname: 'Traditional Council Chairman'},
{name_first: 'Sunday', name_last: 'Mulbah', salut: 'Mr.',  gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Esther', name_last: 'Koryon', salut: 'Mrs.',  gender: 2, structure_id: 7, community: 'Sheriff Quarter', agencyname: 'County  Gender Coordinator'},
{name_first: 'Musa', name_last: 'Keselee',   gender: 1, structure_id: 10, community: 'Voinjama'},
{name_first: 'Musu', name_last: 'Freeman',   gender: 2, structure_id: 6, community: 'SKT'},
{name_first: 'Nathaniel', name_last: 'Getty',   gender: 1, structure_id: 3, community: 'Palala'},
{name_first: 'Nathaniel', name_last: 'Waha',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Neewray', name_last: 'Ophoriee',   gender: 1, structure_id: 31, community: 'Gaye Town'},
{name_first: 'Nelson', name_last: 'Gbegbeh',   gender: 1, structure_id: 4, community: 'Kpaai Town'},
{name_first: 'Nelson', name_last: 'Keyen',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Norah', name_last: 'Yarkpawolo',   gender: 2, structure_id: 4, community: 'Melenta'},
{name_first: 'Norwah', name_last: 'Geryellee',   gender: 2, structure_id: 4, community: 'Tarsah'},
{name_first: 'Numene', name_last: 'Flomo',   gender: 1, structure_id: 6, community: 'Sinyea'},
{name_first: 'Nuwoe', name_last: 'Kollie',   gender: 1, structure_id: 4, community: 'Zoweinta'},
{name_first: 'Nyamah', name_last: 'Gbayeh',   gender: 2, structure_id: 4, community: 'Sekieta'},
{name_first: 'Nyamah', name_last: 'Saybah',   gender: 2, structure_id: 6, community: 'Yarwalee'},
{name_first: 'Nyamah', name_last: 'Sulonteh',   gender: 2, structure_id: 6, community: 'Phebe'},
{name_first: 'Nyamah', name_last: 'Tokpah',   gender: 2, structure_id: 6, community: 'Karyeata'},
{name_first: 'Nyuma', name_last: 'Ngasakorjah',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Obadiah', name_last: 'Kermue',   gender: 1, structure_id: 3, community: 'Kpaai Town'},
{name_first: 'Ojuku', name_last: 'Kimsw',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'O***777***uenwon', name_last: 'Gono',   gender: 1, structure_id: 2, community: 'Lofa Road community, Gbarnga', agencyname: 'BIN Commander'},
{name_first: 'Oretha', name_last: 'Dennis',   gender: 2, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Oretha', name_last: 'Gee',   gender: 2, structure_id: 33, community: 'Sayuo Town'},
{name_first: 'Oretha', name_last: 'Krayou',   gender: 2, structure_id: 33, community: 'Dweh Town'},
{name_first: 'Osoko', name_last: 'Kerkulah',   gender: 1, structure_id: 4, community: 'Zoweinta'},
{name_first: 'Othelloe', name_last: 'Potokenor',   gender: 1, structure_id: 9, community: 'Sorlomba'},
{name_first: 'David', name_last: 'Zarwu', salut: 'Past.',  gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Patience', name_last: 'Harris',   gender: 2, structure_id: 29, community: 'Toe Town'},
{name_first: 'Patience', name_last: 'Kimwon',   gender: 2, structure_id: 31, community: 'Zleh Town'},
{name_first: 'Patience', name_last: 'Zelee',   gender: 2, structure_id: 33, community: 'Deleayee'},
{name_first: 'Patrick', name_last: 'Quenneh',   gender: 1, structure_id: 4, community: 'Baila'},
{name_first: 'Paul', name_last: 'Myers',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Paye', name_last: 'Cooper',   gender: 1, structure_id: 28, community: 'Bah Town'},
{name_first: 'Perrison', name_last: 'Wea',   gender: 1, structure_id: 31, community: 'Gbeayea'},
{name_first: 'Peter', name_last: 'Bossoe',   gender: 1, structure_id: 32, community: 'Ziah Town'},
{name_first: 'Peter', name_last: 'Daniel',   gender: 1, structure_id: 5, community: 'Peter Town'},
{name_first: 'Peter', name_last: 'Kerkulah',   gender: 1, structure_id: 6, community: 'Nai'},
{name_first: 'Peter', name_last: 'Mulbah',   gender: 1, structure_id: 5, community: 'Sinyea'},
{name_first: 'Peter', name_last: 'Toe',  suffix: 'Jr.', gender: 1, structure_id: 29, community: 'Toe Town'},
{name_first: 'Peter', name_last: 'Willie',   gender: 1, structure_id: 29, community: 'Pokor'},
{name_first: 'Princess', name_last: 'Quindeh',   gender: 2, structure_id: 29, community: 'Sennehwen'},
{name_first: 'Quedy', name_last: 'Byne',   gender: 1, structure_id: 33, community: 'Druglor'},
{name_first: 'Queta', name_last: 'Baba',   gender: 2, structure_id: 6, community: 'Balama'},
{name_first: 'Queta', name_last: 'Flomo',   gender: 2, structure_id: 6, community: 'Gokai'},
{name_first: 'Ragan', name_last: 'Kpannah',   gender: 1, structure_id: 4, community: 'Tomato Camp'},
{name_first: 'Rebecca', name_last: 'Gee',   gender: 2, structure_id: 33, community: 'Boundary'},
{name_first: 'Rebecca', name_last: 'Glay',   gender: 2, structure_id: 32, community: 'Glay Town'},
{name_first: 'Rebecca', name_last: 'Kollie',   gender: 1, structure_id: 4, community: 'Zoweinta'},
{name_first: 'Regina', name_last: 'Beh',   gender: 2, structure_id: 29, community: 'Pokor'},
{name_first: 'Edwine', name_last: 'Borsou', salut: 'Rev.',  gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Jimmy', name_last: 'Nlear', salut: 'Rev.',  gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Roddicious', name_last: 'Kollie',   gender: 1, structure_id: 7, community: 'Doe Hill', agencyname: 'County EPS Commander'},
{name_first: 'Rufus', name_last: 'Sumo',   gender: 1, structure_id: 13, community: 'Yeala'},
{name_first: 'Saa', name_last: 'Toma',   gender: 1, structure_id: 11, community: 'Tobogizissou'},
{name_first: 'Saah', name_last: 'Kai',   gender: 1, structure_id: 9, community: 'Jimita'},
{name_first: 'Saah', name_last: 'Keyo',   gender: 1, structure_id: 9, community: 'Geleimai'},
{name_first: 'Saah', name_last: 'Korsue',   gender: 1, structure_id: 8, community: 'Foya City'},
{name_first: 'Sam', name_last: 'Kollie',   gender: 1, structure_id: 2, community: 'Civil Compound, Gbarnga', agencyname: 'Head of County LRA Office'},
{name_first: 'Sampson', name_last: 'Chapoyee',   gender: 1, structure_id: 31, community: 'Polar '},
{name_first: 'Saywala', name_last: 'Sorsor',   gender: 1, structure_id: 11, community: 'Lobobah'},
{name_first: 'Sediki', name_last: 'Konneh',   gender: 1, structure_id: 28, community: 'Toe Town'},
{name_first: 'Sekou', name_last: 'Sheriff',   gender: 1, structure_id: 13, community: 'Borkeza'},
{name_first: 'Seleke', name_last: 'Komala',   gender: 1, structure_id: 12, community: 'Zorzor'},
{name_first: 'Sia', name_last: 'Morris',   gender: 2, structure_id: 9, community: 'Foya'},
{name_first: 'Sia', name_last: 'Williams',   gender: 2, structure_id: 9, community: 'Foya'},
{name_first: 'Sobondo', name_last: 'Saa',   gender: 2, structure_id: 9, community: 'Shelloe'},
{name_first: 'Solomon', name_last: 'Gray',   gender: 1, structure_id: 6, community: 'Gokai'},
{name_first: 'Sophie', name_last: 'Waylee',   gender: 2, structure_id: 33, community: 'Ziah Town'},
{name_first: 'Sue', name_last: 'Cheh',   gender: 2, structure_id: 33, community: 'Ziah Town'},
{name_first: 'Sulonteh', name_last: 'Yeaba',   gender: 1, structure_id: 5, community: 'Gbarngata'},
{name_first: 'Suwah', name_last: 'Dennis',   gender: 2, structure_id: 13, community: 'Zealakpaila'},
{name_first: 'Tamay', name_last: 'Qualpa',   gender: 2, structure_id: 5, community: 'Suakoko '},
{name_first: 'Tamba', name_last: 'Fayiah',   gender: 1, structure_id: 9, community: 'Tarmah'},
{name_first: 'Tarnue', name_last: 'Gbelee',   gender: 1, structure_id: 13, community: 'Wakesu'},
{name_first: 'Taynee', name_last: 'Guzeh',   gender: 2, structure_id: 13, community: 'Fassawalazu'},
{name_first: 'Teresa', name_last: 'Turker',   gender: 2, structure_id: 4, community: 'Tomato Camp'},
{name_first: 'Theresa', name_last: 'Fayia',   gender: 2, structure_id: 9, community: 'Foya'},
{name_first: 'Thomas', name_last: 'Fallah',   gender: 1, structure_id: 9, community: 'Foya City'},
{name_first: 'Thomas', name_last: 'Kullie',   gender: 1, structure_id: 11, community: 'Voinjama'},
{name_first: 'Thomas', name_last: 'Tamba',   gender: 1, structure_id: 9, community: 'Bandilabenga'},
{name_first: 'Timothy', name_last: 'Saye',   gender: 1, structure_id: 4, community: 'Quapa Town'},
{name_first: 'Tina', name_last: 'Karr',   gender: 2, structure_id: 31, community: 'Deblay'},
{name_first: 'Titoe', name_last: 'Lolin', salut: 'Col.',  gender: 1, structure_id: 7, community: 'Army Barrack', agencyname: 'County LNP Commander'},
{name_first: 'Torwon', name_last: 'Kerbel',   gender: 1, structure_id: 4, community: 'Zoweinta'},
{name_first: 'Towan', name_last: 'Wokpeh',   gender: 2, structure_id: 5, community: 'Suakoko '},
{name_first: 'Varbah', name_last: 'Kollie',   gender: 2, structure_id: 7, community: 'Salayea (outside)', agencyname: 'County Rural Women Chair'},
{name_first: 'Varlee', name_last: 'Kamara',   gender: 1, structure_id: 5, community: 'Suakoko '},
{name_first: 'Victor', name_last: 'Bahflahn',   gender: 1, structure_id: 31, community: 'Zleh Town'},
{name_first: 'Victor', name_last: 'Paye',   gender: 1, structure_id: 28, community: 'Dougee'},
{name_first: 'Victoria', name_last: 'Sonh',   gender: 2, structure_id: 31, community: 'Zuajah'},
{name_first: 'Victory', name_last: 'Gbarnjah',   gender: 2, structure_id: 3, community: 'Palala'},
{name_first: 'Vister', name_last: 'Kyne',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'Voity', name_last: 'Klo',   gender: 1, structure_id: 30, community: 'Polar '},
{name_first: 'Wahma', name_last: 'Chea',   gender: 1, structure_id: 33, community: 'Wrabo'},
{name_first: 'Wallace', name_last: 'Darh',   gender: 1, structure_id: 32, community: 'Flah'},
{name_first: 'Wessely', name_last: 'Gowela',   gender: 1, structure_id: 30, community: 'Zleh Town'},
{name_first: 'William', name_last: 'Dormue',   gender: 1, structure_id: 4, community: 'Sekieta'},
{name_first: 'Williams', name_last: 'Gee',   gender: 1, structure_id: 31, community: 'Cheansla'},
{name_first: 'Williams', name_last: 'Taylor',   gender: 1, structure_id: 9, community: 'Tennessadu'},
{name_first: 'Wolobah', name_last: 'Nyankoi',   gender: 1, structure_id: 12, community: 'Kpassagizia'},
{name_first: 'Yama', name_last: 'Partee',   gender: 2, structure_id: 13, community: 'Passama'},
{name_first: 'Yarmeh', name_last: 'Weedor',   gender: 2, structure_id: 12, community: 'Zorzor'},
{name_first: 'Yassah', name_last: 'Varbah',   gender: 2, structure_id: 12, community: 'Zorzor'},
{name_first: 'Zayzay', name_last: 'Kpakolo',   gender: 1, structure_id: 11, community: 'Kolliemai'}

                          ])



peeps = Person.all
peeps.each do |p|
  Membership.create(structure_id: p.structure_id, person_id: p.id)
end